Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2020-06, with the labels that each got.

#178 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#182 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#184 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: cla: yes, context: full

#185 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#187 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#190 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#196 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: cla: yes

#205 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#207 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#210 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#214 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#218 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#225 docs(samples): create and delete scheduled query
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateScheduledQuery.java
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/DeleteScheduledQuery.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/CreateScheduledQueryIT.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/DeleteScheduledQueryIT.java
Labels: cla: yes

#226 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#228 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
