Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2020-05, with the labels that each got.

#157 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: cla: yes, context: full

#159 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#164 chore: bump dep post release
  README.md
  synth.metadata
Labels: cla: yes, context: none

#166 fix: restore GAPIC v2 retry configs
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClient.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceSettings.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/package-info.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/DataTransferServiceStub.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/DataTransferServiceStubSettings.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/GrpcDataTransferServiceStub.java
  google-cloud-bigquerydatatransfer/src/test/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClientTest.java
  synth.metadata
Labels: cla: yes, context: full

#170 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#174 deps: bump shared-deps version and add back certain test deps
  pom.xml
Labels: automerge, cla: yes

#176 bazel: update protobuf, rules_go, gazelle, and gapic-generator-go versions
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CheckValidCredsRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CheckValidCredsResponse.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/CreateTransferConfigRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSource.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceParameter.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DeleteTransferConfigRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DeleteTransferRunRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/EmailPreferences.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetDataSourceRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetTransferConfigRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/GetTransferRunRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListDataSourcesRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListDataSourcesResponse.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferConfigsRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferConfigsResponse.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferLogsRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferLogsResponse.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ListTransferRunsResponse.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleOptions.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleTransferRunsRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/ScheduleTransferRunsResponse.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/StartManualTransferRunsRequest.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/StartManualTransferRunsResponse.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferConfig.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferMessage.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferRun.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferState.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferType.java
  proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/UpdateTransferConfigRequest.java
  synth.metadata
Labels: cla: yes, context: full

#177 docs(samples): migrate samples into client
  pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/QuickstartSample.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/QuickstartSampleIT.java
Labels: automerge, cla: yes

#180 docs(samples): add codeowner file
  .github/CODEOWNERS
Labels: automerge, cla: yes
