Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2020-10, with the labels that each got.

#413 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#414 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, cla: yes

#422 ci: restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
Labels: automerge, cla: yes

#425 docs(samples): add update credentials
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/UpdateCredentials.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/UpdateCredentialsIT.java
Labels: cla: yes

#426 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#427 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#429 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#433 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#434 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#438 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#441 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#446 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#449 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#424 refactor(samples): schedule backfill
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/ScheduleBackFill.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/ScheduleBackFillIT.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#450 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#452 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#456 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#458 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#460 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#466 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#468 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#471 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#473 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#474 ci: restrict nightly samples jobs to run only in snippets/
  .kokoro/build.sh
Labels: automerge, cla: yes

#477 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: cla: yes, context: full
