Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2020-11, with the labels that each got.

#481 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#486 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#488 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#490 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#489 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, cla: yes

#492 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#494 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#497 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#499 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#502 docs(samples): add create teradata transfer
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateTeradataTransfer.java
Labels: api: bigquerydatatransfer, cla: yes

#504 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#509 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#510 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#507 docs(samples): add create redshift transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateRedshiftTransfer.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#516 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#511 refactor(samples): update params in teradata transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateTeradataTransfer.java
Labels: api: bigquerydatatransfer, automerge, cla: yes, samples

#519 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#523 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#521 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#527 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#529 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#524 docs(samples): add create ads transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateAdsTransfer.java
Labels: api: bigquerydatatransfer, cla: yes, samples, waiting on backend

#525 docs(samples): add create campaign manager transfer
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateCampaignmanagerTransfer.java
Labels: api: bigquerydatatransfer, cla: yes, samples, waiting on backend

#530 docs(samples): add create ad manager transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateAdManagerTransfer.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#532 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#535 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#536 docs(samples): create play transfer
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreatePlayTransfer.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#537 docs(samples): add create youtube channel transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateYoutubeChannelTransfer.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#538 docs(samples): add create youtube owner channel transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateYoutubeContentOwnerTransfer.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#540 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#541 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full, samples

#542 chore: Remove spurious build warnings by deleting--include_source_info from .bazelrc
  grpc-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceGrpc.java
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#543 refactor(samples): updates params and comments
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateAdManagerTransfer.java
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateAdsTransfer.java
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateCampaignmanagerTransfer.java
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreatePlayTransfer.java
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateYoutubeChannelTransfer.java
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateYoutubeContentOwnerTransfer.java
Labels: api: bigquerydatatransfer, cla: yes, samples
