Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2020-09, with the labels that each got.

#317 build(ci): enable auto-release in this repo
  .github/workflows/auto-release.yaml
Labels: automerge, cla: yes

#321 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#322 docs(samples): add create scheduled query with service account
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateScheduledQueryWithServiceAccount.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/CreateScheduledQueryWithServiceAccountIT.java
Labels: cla: yes

#324 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#328 docs(samples): add run notification
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/RunNotification.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/RunNotificationIT.java
Labels: cla: yes

#330 build(ci): add Documentation to not-autorelease script
  .github/workflows/auto-release.yaml
Labels: automerge, cla: yes

#332 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#333 docs(samples): add run history
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/RunHistory.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/RunHistoryIT.java
Labels: cla: yes

#336 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#337 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#338 chore: generate CODEOWNERS from templates
  .repo-metadata.json
Labels: automerge, cla: yes

#339 [CHANGE ME] Re-generated to pick up changes from self.
  .github/CODEOWNERS
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#344 build(ci): set up secrets(env vars) for samples ITs
  .kokoro/build.sh
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  synth.py
Labels: cla: yes

#334 docs(samples): add run details
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/RunDetails.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/RunDetailsIT.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#345 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#341 refactor(samples): use env variable
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/GetTransferConfigInfoIT.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/ListTransferConfigsIT.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#347 docs(samples): add update transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/UpdateTransferConfig.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/UpdateTransferConfigIT.java
Labels: cla: yes

#348 refactor(samples): update run history it
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/RunHistoryIT.java
Labels: cla: yes

#349 docs(samples): add protobuf.util dependency to enable FieldMaskUtil
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/UpdateTransferConfig.java
Labels: cla: yes

#350 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#356 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#363 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#372 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#374 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: bigquerydatatransfer, cla: yes

#379 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#381 refactor(samples): update transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/UpdateTransferConfig.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/UpdateTransferConfigIT.java
Labels: cla: yes

#383 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#385 docs(samples): add re-enable transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/ReEnableTransferConfig.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/ReEnableTransferConfigIT.java
Labels: cla: yes

#387 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#388 docs(samples): add delete transfer config
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/DeleteTransferConfig.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/DeleteTransferConfigIT.java
Labels: cla: yes

#392 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#389 docs(samples): add copy dataset
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CopyDataset.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/CopyDatasetIT.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#390 docs(samples): add schedule backfill
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/ScheduleBackFill.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/ScheduleBackFillIT.java
Labels: api: bigquerydatatransfer, cla: yes, samples

#394 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
