Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2020-08, with the labels that each got.

#277 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: cla: yes, context: full

#279 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#289 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#291 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#293 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#298 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/workflows/samples.yaml
  synth.metadata
Labels: cla: yes, context: full

#299 refactor(samples): main method
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/CreateScheduledQuery.java
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/DeleteScheduledQuery.java
Labels: cla: yes

#302 fix: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#305 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#300 docs(samples): add get transferconfig info
  samples/snippets/src/main/java/com/example/bigquerydatatransfer/GetTransferConfigInfo.java
  samples/snippets/src/test/java/com/example/bigquerydatatransfer/GetTransferConfigInfoIT.java
Labels: api: bigquerydatatransfer, cla: yes

#307 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none
