Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2021-02, with the labels that each got.

#620 build(java): generate docfx yml on release
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#621 build(java): run linkage monitor as GitHub action
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#624 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#625 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#626 docs: generate sample code in the Java microgenerator
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClient.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/package-info.java
  synth.metadata
Labels: cla: yes, context: full, samples

#627 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#629 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#631 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#636 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#637 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#638 chore: update gapic-generator-java to 0.0.20
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/GrpcDataTransferServiceStub.java
  google-cloud-bigquerydatatransfer/src/test/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClientTest.java
  google-cloud-bigquerydatatransfer/src/test/java/com/google/cloud/bigquery/datatransfer/v1/MockDataTransferServiceImpl.java
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#640 build: reduce download junk in log files
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#644 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/gapic_metadata.json
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#646 ci: test out new sonatype google endpoint
  google-cloud-bigquerydatatransfer-bom/pom.xml
  pom.xml
Labels: api: bigquerydatatransfer, automerge, cla: yes

#650 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#654 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#657 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#666 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#670 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes
