Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2021-08, with the labels that each got.

#957 ci: remove Java 7 branch protection rule
  .github/sync-repo-settings.yaml
Labels: api: bigquerydatatransfer, automerge, cla: yes

#950 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#960 feat!: Java 8 breaking generator changes
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceClient.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferServiceSettings.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/DataTransferServiceStubSettings.java
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/GrpcDataTransferServiceStub.java
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#961 feat: trigger release
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: bigquerydatatransfer, automerge

#967 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#974 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#980 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#981 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/nightly/integration.cfg
  synth.metadata
Labels: cla: yes, api: bigquerydatatransfer, context: full

#986 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#988 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#995 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#999 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#1006 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#1003 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: bigquerydatatransfer, automerge

#1007 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#1009 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: bigquerydatatransfer, automerge

#990 chore: update gapic-generator-java version to 2.1.0
  google-cloud-bigquerydatatransfer/src/main/java/com/google/cloud/bigquery/datatransfer/v1/stub/DataTransferServiceStubSettings.java
  synth.metadata
Labels: cla: yes, api: bigquerydatatransfer, automerge, context: full

#1020 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
  google-cloud-bigquerydatatransfer-bom/pom.xml
  google-cloud-bigquerydatatransfer/pom.xml
  owlbot.py
  pom.xml
  synth.py
  versions.txt
Labels: cla: yes, api: bigquerydatatransfer
