Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2021-09, with the labels that each got.

#1039 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: bigquerydatatransfer, automerge

#1057 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: bigquerydatatransfer

#1067 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: bigquerydatatransfer, automerge

#1074 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: bigquerydatatransfer
