Repository googleapis/java-bigquerydatatransfer, pull requests merged in 2021-05, with the labels that each got.

#804 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#805 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: none

#806 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: bigquerydatatransfer, automerge, cla: yes

#808 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#817 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#822 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#824 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#830 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#831 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: full

#836 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#838 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#840 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#846 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#848 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#851 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes

#854 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerydatatransfer, automerge, cla: yes
